learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views


app_name = 'basic_app'


urlpatterns= [
    path('relative/', views.relative, name='relative'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('other/', views.other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_templates/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)


    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_templates/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_templates/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    context_dict = {'text': 'hallo verden', 'number': 100}
    return render(request, 'basic_app/index.html', context_dict)

@login_required
def special(request):
    return HttpRespsonse("You are logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password: {}". format(username, password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request, 'basic_app/login.html', {})

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel= "stylesheet" href= "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
 <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
     <div class="container">
         <ul class="nav navbar-nav">
             <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
             <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a>
             <a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a>
             <a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a>


    {% if user.is_authenticated %}
       <a class="navbar-link" href="{% url 'logout' %}">Logout</a>
    {% else %}
       <a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>

    {% endif %}

        </ul>
     </div>

 </nav>

<div class="container">

    {% block body_block %}

      {% endblock %}
</div>
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}

{% block body_block  %}

<h1>Velkommen til index</h1>
<h2>Dette er 'index.html page' </h2>

             {% endblock %}

learning_templates/templates/basic_app/login.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}

{% block body_block  %}

<dic class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basic_app:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">

    </form>

</dic>

{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}

{% block body_block  %}
<h1>Velkommen til other</h1>
<h2>This is an example of template inheritance!</h2>
{% endblock  %}

learning_templates/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static  %}

{% block body_block  %}

{% if registered  %}
    <h1>Thank you for registering!</h1>
{% else  %}
<h1>Register here!</h1>
<h3>Fill out the form:</h3>

<form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
     {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="Register">

</form>
{% endif %}
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Velkommen til relativ URL templates</h1>
<a href="{% url 'basic_app:other' %}"> The other page</a>
<a href="{% url 'admin:index' %}">Link to admin</a>
<a href="{% url 'index' %}">Link to index</a>

</body>
</html>